### ISSUE TITLE
DUE ?.?? - INTERNAL REVIEW - Staging Link (Round 1/2)

### ISSUE THREAD

**Issue by johnathonroach** [johnathonroach/testapi#27]
<a href="https://github.com/johnathonroach"><img src="https://avatars3.githubusercontent.com/u/1884440?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [johnathonroach](https://github.com/johnathonroach)**
_Friday Mar 10, 2017 at 20:15 GMT_
_Originally opened as https://github.com/Saxum/SaxumTemplate/issues/27_

----

Saxum - Website Reviewers Guide explains how reviewers can submit good feedback  https://docs.google.com/document/d/10Osv935yjGKb6IICekP_0FSf-mK-WS313RVdjqAhBvU/edit?usp=sharing 

Goal of the review is to ensure we are shipping a quality staging link to the client for review. Outcome of review is a list of revisions for developer to address before it’s client ready. 

TPM shall compile feedback, ensure validity of feedback, ensure feedback matches final scope, and task developer with all needed revisions.

## Tasks
- [ ] Send staging link to internal stakeholders for review, including:
- Digital VP
- Technical Director
- Project’s Technical PM / Producer
- Design lead
- Account lead
- Content lead

- [ ] ensure message includes link to the Saxum - Website Reviewers Guide
- [ ]  Ensure message includes deadline for when feedback is due
- [ ] Ensure message includes brief list of any known aspects of the site that are incomplete (maybe due to missing content, or in-progress development).
