### ISSUE TITLE
DUE ?.?? - LAUNCH

### ISSUE THREAD

**Issue by johnathonroach** [johnathonroach/testapi#31]
<a href="https://github.com/johnathonroach"><img src="https://avatars3.githubusercontent.com/u/1884440?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [johnathonroach](https://github.com/johnathonroach)**
_Friday Mar 10, 2017 at 20:16 GMT_
_Originally opened as https://github.com/Saxum/SaxumTemplate/issues/31_

----

## Registrar: 
???
## Hosting:
???
## Domain: 
???
## IP of production server: 
???

## PRE LAUNCH
- [ ] Ensure all plugins are updated
- [ ] Before launch, remove any plugins no longer used or needed 
- [ ] Confirm all form notification, admin settings, and contact forms are changed to client email address
- [ ] Toggle off site password protection in Flywheel admin
- [ ] Configure GA
- [ ] Ensure the site is configured to index all pages, not just homepage.
- [ ] Ensure Settings/reading/search engine visibility is untoggled..
- [ ] Signup site for google webmaster tools on digital@saxum.com account.
- [ ] connect the Search Console with the Analytics account https://docs.google.com/document/d/16k4mY64M4j9hZR9_9hEKBP7bxPeqvizBl11kIMDKUos/edit
- [ ]  enable cache on flywheel in ADVANCED (if disabled for development)

## DURING LAUNCH
- [ ] Update primary domain in FlyWheel admin (add in the primary domain and all other instructions per the flywheel guide https://getflywheel.com/wordpress-support/go-live-flywheel/
- [ ]  Make DNS change (follow Flywheel instructions https://getflywheel.com/wordpress-support/how-do-i-set-up-my-dns/ )
- [ ] Ensure Facebook app id is updated to primary domain

## POST LAUNCH
- [ ] Test all internal links
- [ ] Test all social shares to ensure they pull up correctly
- [ ] Confirm GA is tracking visitors
- [ ] Site Monitoring setup such as Pingdom
- [ ] Post Launch, grab High-Quality full-screen image of every critical page for marketing use
- [ ] Submit domains to search engines?
- [ ] post the LAUNCH ANNOUNCEMENT in internal saxum channel
